message:
  initteleport: "&aSearching for safe location to teleport to..."
  #Used when teleport delay is larger than 0. This supports placeholders
  #valid placeholders: %hp (hours partial) %mp (minutes partial) %sp (seconds partial) %h (total hours) %m (total minutes) %s(total seconds)
  initteleport_delay: "&aYou will be teleported in &6%s seconds. &aDo not move!"
  teleport_canceled: "&aYou moved! Teleportation canceled"
  #valid placeholders: %posX, %posY, %posZ
  teleport: "&bA safe place has been found! Teleporting to &a%posX %posY %posZ"
  depleted_queue: "&6Locations queue depleted... Forcing generation of a new location"
  #valid placeholders: %hp (hours partial) %mp (minutes partial) %sp (seconds partial) %h (total hours) %m (total minutes) %s(total seconds)
  countdown: "&cYou cannot teleport for another &6%mp minutes %sp seconds"
  #valid placeholders: %world
  no_world_permission: "&cI'm sorry, you cannot rtp in %world"
  empty_queue: "&cThere are no locations available for this world! Try again in a bit or ask an admin to reload the config."
  economy:
    insufficient_funds: "&cYou do not have enough money to rtp!"
    payment: "&aYou just paid &b%price &ato rtp!"
  sign:
    - "<aqua>[RandomTeleport]</aqua>"
    - "teleport to %world"
#The amount of pre-generated locations in the queue
queue:
  size: 5
  #The delay in ticks (20 ticks = 1 second) for the queue to kick in, lower is faster but searching at the same time as teleporting the player
  #can be heavy on the server, if the player that just got teleported also needs to generate chunks. So generally not a bad idea to delay it a least a little bit
  init_delay: 60
worlds:
  world:
    #Use the worldborder (if set) for offset. This is the vanilla worldborder.
    use_worldborder: true
    #Whether or not the user needs the rtp.world.<worldname> permission
    needs_world_permission: false
    #Radius and offset will be ignored if use_worldborder is true.
    radius: 21474836
    offsetX: 0
    offsetZ: 0
teleport:
  #m = minutes, s = seconds
  #default: "60m"
  cooldown: "60m"
  #default: "0s"
  delay: "0s"
  cancel_on_move: true
  #If players die within this time after RTP'ing they wont lose anything.
  #Set to 0 to disable. Default "10s"
  death_timer: "10s"
#Plugins to take into consideration when teleporting. A player will not be teleported in those regions
#Currently supports Factions (FactionsUUID), WorldGuard, GriefPrevention, RedProtect, Towny
#If you want more plugins to be supported: https://github.com/DarkEyeDragon/RandomTeleport/issues
plugins:
  - Factions
  - WorldGuard
  - GriefPrevention
  - RedProtect
  - Towny
debug:
  #Safe location added for world(3/5)
  #Location removed from world(2/5)
  show_queue_population: true
economy:
  price: 0
#The items to blacklist. Block uses the Material enum for names, find all of them here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#Blocks also support Tags ($PRESSURE_PLATES = all types of pressure plates) a full list can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Tag.html
#All Tags are prefixed with $
#Also supports regex.
blacklist:
  global:
    block:
      - LAVA
      - CACTUS
      - $FIRE
      - MAGMA_BLOCK
      - TRIPWIRE
      - $PRESSURE_PLATES
  overworld:
    biome:
      - ".*OCEAN"
    block: []
  nether:
    biome: []
    block: []
  end:
    biome: []
    block: []
