messages:
  initteleport: "&aSearching for safe location to teleport to..."
  #Used when teleport delay is larger than 0. This supports placeholders
  #valid placeholders: %hp (hours partial) %mp (minutes partial) %sp (seconds partial) %h (total hours) %m (total minutes) %s(total seconds)
  initteleport-delay: "&aYou will be teleported in &6%s seconds. &aDo not move!"
  teleport-canceled: "&aYou moved! Teleportation canceled"
  #valid placeholders: %posX, %posY, %posZ
  teleport: "&bA safe place has been found! Teleporting to &a%posX %posY %posZ"
  #valid placeholders: %hp (hours partial) %mp (minutes partial) %sp (seconds partial) %h (total hours) %m (total minutes) %s(total seconds)
  countdown: "&cYou cannot teleport for another &6%mp minutes %sp seconds"
  #valid placeholders: %world
  no-world-permission: "&cI'm sorry, you cannot rtp in %world"
  empty-queue: "&cThere are no locations available for this world! Try again in a bit or ask an admin to reload the config."
  invalid-default-world: "&cThe default world is not set or is invalid. Cannot teleport you. Contact an admin to fix this issue."
  economy:
    insufficient-funds: "&cYou do not have enough money to rtp!"
    payment: "&aYou just paid &b%price &ato rtp!"
  sign:
    - "<aqua>[RandomTeleport]</aqua>"
    - "teleport to %world"
#The amount of pre-generated locations in the queue
queue:
  size: 5
  #The delay in ticks (20 ticks = 1 second) for the queue to kick in, lower is faster but searching at the same time as teleporting the player
  #can be heavy on the server, if the player that just got teleported also needs to generate chunks. So generally not a bad idea to delay it a least a little bit
  init-delay: 60
worlds:
  world:
    #Use the worldborder for offset. This is the vanilla worldborder.
    use-worldborder: true
    #Whether or not the user needs the rtp.world.<worldname> permission
    needs-world-permission: false
    #Radius and offset will be ignored if use-worldborder is true.
    radius: 21474836
    offsetX: 0
    offsetZ: 0
    price: 0
teleport:
  cooldown: 72000
  #default: 0
  delay: 0
  cancel-on-move: true
  #If players die within this time after RTP'ing they wont lose anything.
  #Set to 0 to disable. Default "10s"
  death-timer: 200
  #The particle to display when the player is teleporting. NONE for no particles. A full list can be found on
  #https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  #You also need to provide the amount of particles.
  #Default: TOTEM:20
  particle: TOTEM:20
  use-default-world: false
  default-world: "world"
#Plugins to take into consideration when teleporting. A player will not be teleported in those regions
#Currently supports Factions (FactionsUUID), WorldGuard, GriefPrevention, RedProtect, Towny
#If you want more plugins to be supported: https://github.com/DarkEyeDragon/RandomTeleport/issues
plugins:
  - Factions
  - WorldGuard
  - GriefPrevention
  - RedProtect
  - Towny
debug:
  #Safe location added for world(3/5)
  #Location removed from world(2/5)
  show-queue-population: true
  #Shows debug messages in game on the execution times of the entire teleport process.
  #Normally only enable to figure out what is causing teleport delays.
  show-execution-times: false
#Default price for worlds without a price defined.
#0 to disable
economy:
  default-price: 0
#The items to blacklist. Block uses the Material enum for names, find all of them here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#Blocks also support Tags ($PRESSURE-PLATES = all types of pressure plates) a full list can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Tag.html
#All Tags are prefixed with $
#Also supports regex.
blacklist:
  global:
    block:
      - LAVA
      - CACTUS
      - $FIRE
      - MAGMA-BLOCK
      - TRIPWIRE
      - $PRESSURE-PLATES
  overworld:
    biome:
      - ".*OCEAN"
    block: []
  nether:
    biome: []
    block: []
  end:
    biome: []
    block: []
