message:
  initteleport: "&aSearching for safe location to teleport to..."
  teleport: "&bA safe place has been found! Teleporting..."
  #valid placeholders: %mp (minutes partial) %sp (seconds partial) %m (total minutes) %s(total seconds)
  countdown: "&cYou cannot teleport for another &6%mp minutes %sp seconds"
  nopermission: "&cYou do not have permission to execute this command!"
  blacklisted: "&cI am sorry, that world is blacklisted!"
#The amount of pre-generated locations in the queue
queue:
  size: 10

size:
  #Use the worldborder (if set) for offset
  use_worldborder: true
  #Will be ignored if use_worldborder is true
  radius: 21474836
  offsetX: 0
  offsetZ: 0
teleport:
  #m = minutes, s = seconds
  #default: "60m"
  cooldown: "60m"
blacklist:
  isWhitelist: false
  worlds:
    - "world_nether"
    - "world_the_end"
#Plugins to take into consideration when teleporting
#Currently supports FactionsUUID and WorldGuard
#If you want more plugins to be supported: https://github.com/DarkEyeDragon/RandomTeleport/issues
plugins:
  - "Factions"
  - "WorldGuard"