message:
  initteleport: "&aSearching for safe location to teleport to..."
  #valid placeholders: %mp (minutes partial) %sp (seconds partial) %m (total minutes) %s(total seconds)
  countdown: "&cYou cannot teleport for another &6%mp minutes %sp seconds"
  nopermission: "&cYou do not have permission to execute this command!"
#m = minutes, s = seconds
cooldown: "60m"