name: RandomTeleport
version: ${project.version}
main: me.darkeyedragon.randomtp.RandomTeleport
api-version: 1.13
authors: [DarkEyeDragon]
softdepend:
  - Factions
  - WorldGuard
  - GriefPrevention
description: Yeet a player to a random location, and hopefully they won't die in the process
permissions:
  rtp.teleport.*:
    description: give all rtp permissions
    children:
      rtp.teleport.self: true
      rtp.teleport.other: true
      rtp.teleport.bypass: true
      rtp.teleport.world: true
      rtp.world.bypass: true
  rtp.teleport.self:
    description: random teleport yourself
  rtp.teleport.other:
    description: random teleport others
  rtp.teleport.world:
    description: random teleport to any desired non blacklisted world
  rtp.teleport.bypass:
    description: bypass the cooldown